name: simple_eda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - jupyter
  - ipywidgets
  - seaborn
  - pandas
  - pip
  - pyarrow
  - pip:
    - wandb
    - ydata-profiling
    - protobuf==3.20
